version: '3'

services:
  wp:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ${WP_APP_DIR}:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp_content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp_content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
    links:
      - db

  # wpcli:
  #   image: wordpress:cli
  #   volumes:
  #     - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
  #     - ${WP_APP_DIR}:/var/www/html
  #   environment:
  #     WORDPRESS_DB_HOST: db
  #     WORDPRESS_DB_NAME: "${DB_NAME}"
  #     WORDPRESS_DB_USER: root
  #     WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
  #   depends_on:
  #     - db
  #     - wp

  # pma:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
  #     PMA_HOST: db
  #     PMA_PORT: 3306
  #     MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
  #     UPLOAD_LIMIT: 50M
  #   ports:
  #     - ${EXTERNAL_IP}:8080:80
  #   links:
  #     - db

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # expose the db port to host local for debugging, comment it out if not needed
    command:
      [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    volumes:
      - ${WP_DATA_DIR}:/docker-entrypoint-initdb.d
      - ${WP_DB_DIR}:/var/lib/mysql
      - ${MYSQL_CONF_DIR}/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

  nginx:
    image: nginx:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${EXTERNAL_IP}:80:80
      - ${EXTERNAL_IP}:443:443 # https
    volumes:
      - ${CERT_DIR}:/etc/certs
      - ./config/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx.proxy_params:/etc/nginx/proxy_params
    depends_on:
      - wp
    links:
      - wp
